### ISSUE TITLE
commit access / create a branch for category overlapping?

### ISSUE THREAD

**Issue by casz** [TimonVS/release-drafter-test-repo#17]
@TimonVS in trying to fix https://github.com/release-drafter/release-drafter/issues/403

I would appreciate being able to generate one with overlapping categories.

**Comment by TimonVS** [comment]
Added you as a collaborator, see https://github.com/TimonVS/release-drafter-test-repo/pull/3#issuecomment-581135500 :)

**Comment by casz** [comment]
I think will create a separate branch for "duplicate" than 🙇
